name: Upload Release Asset

on: push

jobs:
    build:
        name: Upload Release Asset
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: Upload
              uses: actions/github-script@v3
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      const fs = require('fs');
                      const path = require('path');
                      const release_id = '${{ steps.create_release.outputs.id }}';
                      for (let file of await fs.readdirSync('./')) {
                        if (path.extname(file) === '.vsix') {
                          console.log('uploadReleaseAsset', file);
                          const filePath = path.join('./', file);
                          const fileData = fs.readFileSync(filePath);
                          await github.repos.uploadReleaseAsset({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            release_id: release_id,
                            name: path.basename(file),
                            data: fileData,
                            headers: {
                              'content-length': fileData.length,
                              'content-type': 'application/octet-stream',
                            },
                          });
                        }
                      }
